site_name: AlmaCookBook
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Conda:
    - 'Overview': 'conda/overview.md'
    - 'Basics': 'conda/basics.md'
  - Workflows:
    - 'Singularity and docker': 'workflows/containers.md'    
    - 'Nextflow': 'workflows/nextflow.md'
    - 'nf-core 1) sanity check': 'workflows/nf-core-1.md'

  - FAQs:
    - 'FAQs': 'faqs/faqs.md'
  - Training:
    - 'overview': 'training/overview.md'
    - 'python intro': 'https://icr-sc-training.github.io/intro-to-python/'  
theme:
  name: material  
  logo: assets/icr_svg_logo.svg  
  favicon: assets/icr_svg_logo.svg  
  palette:
    primary: pink  
    accent: deep orange  
