site_name: AlmaCookBook
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - First Steps: 'first_steps.md'
  - Scientific tools:
    - Overview: 'tools/overview.md'
    - Container tools: 'tools/container-tools.md'
    - Mamba tools: 'tools/mamba-tools.md'
  - IDEs:
    - 'VSCode': 'ides/vscode.md'
    - 'remote-ssh': 'ides/remote.md'            
  - Environments:    
    - Basics: 'conda/basics.md'
    - 'Mamba/Conda the first time': 'conda/mamba-first.md'    
    - Mamba environments': 'conda/mamba-venvs.md'    
    - Python:      
      - python scripts: 'conda/python-scripts.md'
      - python jupyter ondemand: 'conda/python-ondemand.md'
      - python-venv: 'conda/python-venv.md'
    - R:
      - R scripts: 'conda/r-scripts.md'
      - R installs from github: 'conda/r-github.md'
      - RStudio ondemand: 'conda/r-ondemand.md'  
  - Nextflow:
    #- nextflow vs slurm: 'workflows/nextflow.md'  
    - Nextflow version: 'workflows/nextflow-envs.md'
    - nf-core Install and test: 'workflows/nf-core-1.md'      
    - Recipes:
      - 'nf-core sarek': 'workflows/nf-core-2.md'
      - 'epi2me-labs': 'workflows/recipe-nf-epitome.md'
  - Containers:
      - 'Singularity and docker': 'workflows/containers.md'  
  - Recipes:
    - 'Matlab-From-Python': 'recipes/matlab-python.md'
    - 'TensorFlow-On-GPU': 'recipes/tensorflow-gpu.md'
  - FAQs:
    - 'FAQs': 'faqs/faqs.md'
  #- Training:
  #  - 'python intro': 'https://almacookbook.github.io/intro-to-python/'
theme:
  name: material
  logo: assets/icr_svg_logo.svg  
  favicon: assets/icr_svg_logo.svg  
  palette:
    primary: pink  
    accent: deep orange  
  features:
    - content.code.copy
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
