site_name: AlmaCookBook
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Conda:
    - 'Overview': 'conda/overview.md'
    - 'Basics': 'conda/basics.md'
  - Workflows:
    - 'Singularity and docker': 'workflows/containers.md'
    - 'Nextflow': 'workflows/nextflow.md'
  - Training:
    - 'overview': 'training/overview.md'
    - 'python intro': 'https://icr-sc-training.github.io/intro-to-python/'  
theme:
  name: material
  logo: assets/icr_svg_logo.svg
  favicon: assets/icr_svg_logo.svg
  palette:
    primary: white
