site_name: AlmaCookBook
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Conda:
    - 'Overview': 'conda/overview.md'
    - 'Basics': 'conda/basics.md'
  - OnDemand:
    - 'Overview': 'ondemand/overview.md'
    - 'Python JupyterNotebook': 'ondemand/jupyter.md'
    - 'RStudio': 'ondemand/RStudio.md'
  - Nextflow:
    - NF-CORE:
      - 'nf-core 1: Install and test': 'workflows/nf-core-1.md'
      - 'nf-core 2: Sarek': 'workflows/nf-core-2.md'
    - Other:
      - 'Nextflow': 'workflows/nextflow.md'
  - Containers:
      - 'Singularity and docker': 'workflows/containers.md'
  - IDEs and standards:
    - Good practices:
      - 'Continuous Integration': 'ides/cicd.md'
      - 'Python good practices': 'ides/python.md'
    - IDEs:
      - 'remote-ssh': 'ides/remote.md'
      - 'VSCode': 'ides/vscode.md'
  - FAQs:
    - 'FAQs': 'faqs/faqs.md'
  - Training:
    - 'python intro': 'https://almacookbook.github.io/intro-to-python/'
theme:
  name: material  
  logo: assets/icr_svg_logo.svg  
  favicon: assets/icr_svg_logo.svg  
  palette:
    primary: pink  
    accent: deep orange  
  features:
    - content.code.copy
markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
