site_name: AlmaCookBook
nav:
  - Home: 'index.md'
  - About: 'about.md'
  - Conda:
    - 'Overview': 'conda/overview.md'
    - 'Basics': 'conda/basics.md'
  - Workflows:
    - 'Nextflow': 'workflows/nextflow.md'
theme:
  name: material
  logo: assets/icr_svg_logo.svg
  favicon: assets/icr_svg_logo.svg
  palette:
    primary: white